version: "2"
services:
  pg_workshop:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    command: "/bin/true"
    volumes:
      - .:/code
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=workshop
    # depends_on:
    #      - db
    command: "/bin/true"
    links:
      - db
  # db_setup:
  #   extends: base
  #   command: "/bin/bash -c '/code/scripts/setup_db.sh'"
  #   links:
  #     - db
  db:
    image: postgres:9.5
    volumes:
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=workshop
