version: "2"
services:
  pg_workshop:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    command: "/bin/true"
    volumes:
      - .:/code
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=workshop
    command: "/bin/true"
    links:
      - db
  db:
    image: postgres:9.5
    volumes:
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./resources/2015-Q2-Trips-History-Data.csv:/opt/data.csv
      - ./resources/sample-500k.csv:/opt/data_events.csv
      - ./resources/test.csv:/opt/test.csv
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=workshop
